sharded-benchmark:
    env: PongDeterministic-v4
    run: shard
    resources:
        cpu:
             eval: "spec.config.num_workers + spec.config.optimizer.shards + 2"
        # driver_cpu_limit: 1
        #gpu: 10
        #driver_gpu_limit: 1
    stop:
        training_iteration: 5
    config:
        num_workers:
             grid_search: [1, 2, 4, 8, 12, 16, 20, 24, 28, 32, 36]
        batch_size: 20
        use_lstm: true
        use_pytorch: false
        vf_loss_coeff: 0.5
        entropy_coeff: -0.01
        gamma: 0.99
        grad_clip: 40.0
        lambda: 1.0
        observation_filter: NoFilter
        reward_filter: NoFilter
        selfdriving: False
        env_config: {}
        model:
            channel_major: false
            dim: 42
            grayscale: true
            zero_mean: false
        optimizer:
            lr: 0.0001
            grads_per_step: 2000
            force: False
            shards:
                grid_search: [2, 4, 8, 12]
